services:
  - type: web
    name: auto-downloader-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    region: oregon
build:
  environment: python
  pythonVersion: 3.10
